### ISSUE TITLE
Got GLException: (0x1280): Invalid enum when running example scenes

### ISSUE THREAD

**Issue by zmx0142857** [YishiMichael/manim3#5]
```sh
$ cd manim3/examples
$ python create.py
```

```text
manim3 v0.1.0
Traceback (most recent call last):
  File "D:\src\manim3\examples\create.py", line 31, in <module>
    CreateExample().run()
  File "D:\src\manim3\manim3\toplevel\scene.py", line 59, in run
    self._run()
  File "D:\src\manim3\manim3\toplevel\scene.py", line 50, in _run
    Toplevel._get_renderer().process_frame()
  File "D:\src\manim3\manim3\toplevel\renderer.py", line 344, in process_frame
    self._render_frame()
  File "D:\src\manim3\manim3\toplevel\renderer.py", line 335, in _render_frame
    self._final_framebuffer.render(self._oit_compose_vertex_array)
  File "D:\src\manim3\manim3\rendering\framebuffers\framebuffer.py", line 100, in render
    Toplevel._get_context().set_blendings(self._blendings)
  File "D:\src\manim3\manim3\toplevel\context.py", line 48, in set_blendings
    gl.glBlendFunci(
  File "D:\app\conda-env\py312\Lib\site-packages\pyglet\gl\lib_wgl.py", line 66, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\conda-env\py312\Lib\site-packages\pyglet\gl\lib.py", line 78, in errcheck
    raise GLException(f'(0x{error}): {msg}')
pyglet.gl.lib.GLException: (0x1280): Invalid enum. An unacceptable value is specified for an enumerated argument.
```
- platform: windows 10
- python version `3.12.1`
- pyglet version `2.0.10`
- OpenGL version `4.3.0 NVIDIA 536.23`

**Comment by YishiMichael** [comment]
Please check out your OpenGL version support. The `gl.glBlendFunci` is supported for OpenGL >= 4.0. The version restriction should be applied in `toplevel/window.py`.

To check out the gl version of the context attached to the created window, after the window creation insert this line:
```py
print(pyglet_window.context.get_info().version)
```
Ideally it should print out `4.3.0`.

**Comment by YishiMichael** [comment]
By the way, what's the platform you are using? It's known that manim3 does not support macOS (for its end of support on OpenGL).

**Comment by zmx0142857** [comment]
Thanks for your reply. My platform is Windows 10 and OpenGL version is exactly 4.3.0

**Comment by YishiMichael** [comment]
Sorry but it seems I cannot bring any help further. My configuration is almost identical with yours, but I cannot reproduce your exception.

**Comment by isning** [comment]
Meet this same here, my platform is Windows 11 with OpenGL `4.3.0 NVIDIA 566.36`, python `3.13.0`, manim3 `0.1.0`

**Comment by isning** [comment]
> Meet this same here, my platform is Windows 11 with OpenGL `4.3.0 NVIDIA 566.36`, python `3.13.0`, manim3 `0.1.0`

And it behave the same way in wsl2 with wslg
