### ISSUE TITLE
GL 错误

### ISSUE THREAD

**Issue by shenjackyuanjie** [YishiMichael/manim3#6]
```
manim3 v0.1.0
Traceback (most recent call last):
  File "V:\githubs\manim\manim3\test1.py", line 32, in <module>
    TextSelectExample().run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 59, in run
    self._run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 50, in _run
    Toplevel._get_renderer().process_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 344, in process_frame
    self._render_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 335, in _render_frame
    self._final_framebuffer.render(self._oit_compose_vertex_array)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\framebuffers\framebuffer.py", line 100, in render
    Toplevel._get_context().set_blendings(self._blendings)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\context.py", line 47, in set_blendings
    gl.glBlendFunci(
  File "V:\githubs\manim\manim3\env\Lib\site-packages\pyglet\gl\lib.py", line 78, in errcheck
    raise GLException(f'(0x{error}): {msg}')
pyglet.gl.lib.GLException: (0x1280): Invalid enum. An unacceptable value is specified for an enumerated argument.
```
运行
https://github.com/YishiMichael/manim3/blob/dev/examples/text_select.py

pyglet.info
```
Platform
------------------------------------------------------------------------------
platform:  Windows-10-10.0.19045-SP0
release:   10
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): V:\githubs\manim\manim3

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.15
pyglet.compat_platform: win32
pyglet.__file__: V:\githubs\manim\manim3\env\Lib\site-packages\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x000002C8C36B8440>
screens[0]: Win32Screen(x=1924, y=2160, width=1920, height=1080)
screens[1]: Win32Screen(x=0, y=0, width=3840, height=2160)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 4
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 8
config['depth_size'] = 24
config['stencil_size'] = 8
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=3061263865312, share=Win32Context(id=3061302909056, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 6)
gl_info.get_vendor(): ATI Technologies Inc.
gl_info.get_renderer(): AMD Radeon RX 580 2048SP

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.xaudio2.adaptation.XAudio2Driver object at 0x000002C8C37B9F10>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'openal32', handle 10000000 at 0x2c8d0c692b0>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_EFX

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab: Wintab Digitizer Services 2.0 (Spec 2.0)
```

**Comment by YishiMichael** [comment]
Restricting moderngl to <=5.9.0 would hopefully fix the issue. Wierd enough, though...
