### ISSUE TITLE
assert error

### ISSUE THREAD

**Issue by shenjackyuanjie** [YishiMichael/manim3#7]
```
manim3 v0.1.0
Traceback (most recent call last):
  File "V:\githubs\manim\manim3\test1.py", line 33, in <module>
    WriteAnimationExample().run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 59, in run
    self._run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 50, in _run
    Toplevel._get_renderer().process_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 344, in process_frame
    self._render_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 332, in _render_frame
    self._oit_framebuffer.render(vertex_array)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\framebuffers\framebuffer.py", line 84, in render
    if (vertex_array_info := vertex_array._vertex_array_info_) is None:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 166, in __get__
    return self._composer(self.get_elements(instance))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 259, in get_elements
    return tuple(memoized_element.get_value() for memoized_element in self._get_memoized_elements(instance))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 223, in _get_memoized_elements
    memoized_elements = self._memoize_elements(self._decomposer(self._method(*(
                                                                ^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\vertex_array.py", line 239, in _vertex_array_info_
    uniform_block_info.verify_structured_field(field)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\vertex_array.py", line 44, in verify_structured_field
    assert field._itemsize_ == self.size
AssertionError
```
running 
https://github.com/YishiMichael/manim3/blob/dev/examples/write_animation.py

**Comment by shenjackyuanjie** [comment]
```
Traceback (most recent call last):
  File "V:\githubs\manim\manim3\test1.py", line 33, in <module>
    WriteAnimationExample().run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 59, in run
    self._run()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\scene.py", line 50, in _run
    Toplevel._get_renderer().process_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 344, in process_frame
    self._render_frame()
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\toplevel\renderer.py", line 332, in _render_frame
    self._oit_framebuffer.render(vertex_array)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\framebuffers\framebuffer.py", line 84, in render
    if (vertex_array_info := vertex_array._vertex_array_info_) is None:
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 166, in __get__
    return self._composer(self.get_elements(instance))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 259, in get_elements
    return tuple(memoized_element.get_value() for memoized_element in self._get_memoized_elements(instance))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\lazy\lazy_descriptor.py", line 223, in _get_memoized_elements
    memoized_elements = self._memoize_elements(self._decomposer(self._method(*(
                                                                ^^^^^^^^^^^^^^^
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\vertex_array.py", line 239, in _vertex_array_info_
    uniform_block_info.verify_structured_field(field)
  File "V:\githubs\manim\manim3\env\Lib\site-packages\manim3\rendering\vertex_array.py", line 44, in verify_structured_field
    assert field._itemsize_ == self.size, f"{field._itemsize_} != {self.size}"
AssertionError: 32 != 24
```
